org 1000h
MSJ DB "INGRESE UN NUMERO DE 1 DIGITO :" 
FIN DB ?
CERO DB "EL NUMERO ES CERO-"
CEFIN DB ? 
UNO DB "EL NUMERO ES UNO-"
UFIN DB ?
DOS DB "EL NUMERO ES DOS-"
DFIN DB ?
TRES DB "EL NUMERO ES TRES-"
TFIN DB ?
CUATRO DB "EL NUMERO ES CUATRO-"
CFIN DB ?
CINCO DB "EL NUMERO ES CINCO-"
CIFIN DB ?
SEIS DB "EL NUMERO ES SEIS-"
SFIN DB ?
SIETE DB "EL NUMERO ES SIETE-"
SIFIN DB ?
OCHO DB "EL NUMERO ES OCHO-"
OFIN DB ?
NUEVE DB "EL NUMERO ES NUEVE-"
NFIN DB ?
FFIN DB "SE INGRESARN DOS CEROS"
FFFIN DB ?
org 1500H 
NUM DB ?
ORG 3000h
subrut: cmp cl,30h
jz escero
cmp cl,31h
jz esuno
cmp cl,32h
jz esdos
cmp cl,33h
jz estres
cmp cl,34h
jz escuatro
cmp cl,35h
jz escinco
cmp cl,36h
jz esseis
cmp cl,37h
jz essiete
cmp cl,38h
jz esocho
cmp cl,39h
jz esnueve
jnz fin
escero: inc dx
MOV BX,OFFSET CERO
MOV AL,OFFSET CEFIN-OFFSET CERO
INT 7
jmp fin
esuno: MOV BX,OFFSET UNO
MOV AL,OFFSET UFIN-OFFSET UNO
INT 7
jmp fin
esdos:MOV BX,OFFSET DOS
MOV AL,OFFSET DFIN-OFFSET DOS
INT 7
jmp fin
estres: MOV BX,OFFSET TRES
MOV AL,OFFSET TFIN-OFFSET TRES
INT 7
jmp fin
escuatro: MOV BX,OFFSET CUATRO
MOV AL,OFFSET CFIN-OFFSET CUATRO
INT 7
jmp fin
escinco: MOV BX,OFFSET CINCO
MOV AL,OFFSET CIFIN-OFFSET CINCO
INT 7
jmp fin
esseis: MOV BX,OFFSET SEIS
MOV AL,OFFSET UFIN-OFFSET SEIS
INT 7
jmp fin
essiete: MOV BX,OFFSET SIETE
MOV AL,OFFSET SIFIN-OFFSET SIETE
INT 7
jmp fin 
esocho: MOV BX,OFFSET OCHO
MOV AL,OFFSET OFIN-OFFSET OCHO
INT 7
jmp fin
esnueve: MOV BX,OFFSET NUEVE
MOV AL,OFFSET NFIN-OFFSET NUEVE
INT 7
jmp fin
fin: RET 
ORG 2000H 
 mov dx,0
 MOV BX, OFFSET MSJ 
MOV AL, OFFSET FIN-OFFSET MSJ
 INT 7
llamada:  MOV BX, OFFSET NUM 
INT 6
mov cl, NUM
call subrut
cmp dx,2
jz finn
jnz llamada
finn:INT 0
end
