 JNZ RESET
 MOV BYTE PTR [BX], 30H
 JMP FINN
 
 RESET: MOV BX, OFFSET SEG ;REINICIAMOS EL ESTADO DE SEGUNDOS
 MOV AL, OFFSET FIN-OFFSET SEG ;PORQUE LO USAMOS MAS ARRIBA
 INT 7
 MOV BX, OFFSET ESPACIO 
 MOV AL, 1 
 INT 7
 MOV AL, 0
 OUT CONT, AL
FINN: MOV AL, 20H
 OUT EOI, AL
 POP AX
 IRET

ORG 3500H
 RUT_F10: PUSH AX
 IN AL, IMR
 XOR AL, 00000010B
 OUT IMR, AL
 MOV AL, 20H
 OUT EOI, AL
 POP AX
 IRET
ORG 2000H

 CLI
 MOV AL, 11111100b ;Activamos el timer
 OUT IMR, AL ; PIC: registro IMR
 
 MOV AL, 10
 OUT INT1, AL ; PIC: registro INT1 (Timer)
 MOV AL, 1
 OUT COMP, AL ; TIMER: registro COMP (No se cual es)
 MOV AL, 0
 OUT CONT, AL ; TIMER: registro CONT
 
 MOV AL, 9;CONFIG INT0
 OUT INT0,AL
 
 STI
 LAZO: JMP LAZO
END
